# Generated by Django 3.2.5 on 2021-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Имя'),
        ),
    ]
