# Generated by Django 3.2.5 on 2021-07-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210710_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='refreshrate',
            field=models.IntegerField(default=2000, verbose_name='PRR'),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='name',
            field=models.CharField(blank=True, default='Noname', max_length=60, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='text',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
